/**
 * GROW Framework-Specific Prompts - Optimized Version
 * Contains step guidance, questions, and examples for the GROW model
 * Balanced for both clarity and efficiency
 */

export const GROW_COACHING_QUESTIONS: Record<string, string[]> = {
  introduction: [
    "Does this framework feel right for what you want to work on today?"
  ],
  goal: [
    "What outcomes would you like to achieve from this conversation?",
    "What does success look like for you?",
    "Why is this important to you right now?",
    "What timeframe are you working with?"
  ],
  reality: [
    "What's your current situation, and what constraints are you facing?",
    "What resources do you have?",
    "What could derail your progress or put this at risk?"
  ],
  options: [
    "What's one option you're considering?",
    "What are the pros and cons of that option?",
    "Would you like to share another option or get AI suggestions?",
    "Which option would you like to move forward with?"
  ],
  will: [
    "What action will you take?",
    "When will you do it?",
    "Who's responsible?",
    "How will you track progress?",
    "What support do you need?"
  ],
  review: [
    "What are the key takeaways from this conversation?",
    "What's your next immediate step?",
    "How are you feeling about moving forward with this plan?"
  ]
};

export const GROW_STEP_GUIDANCE: Record<string, string> = {
  introduction: `INTRODUCTION - Welcome & Consent

FLOW:
1. FIRST TURN: Show welcome message
2. System displays Yes/No buttons
3. SECOND TURN (if user says "yes"): Extract consent and use MINIMAL coach_reflection

FIRST TURN (no user input yet):
coach_reflection: "Would you like to try GROW coaching? It helps you set goals, explore options, and create action plans."
user_consent_given: NOT SET YET

SECOND TURN (user clicked Yes button):
user_consent_given: true
coach_reflection: "[CONSENT_RECEIVED]" (system will advance to Goal automatically)

CRITICAL:
- First turn: Show welcome message
- Second turn: If user says "yes", set user_consent_given=true and coach_reflection="[CONSENT_RECEIVED]"
- Do NOT say "Great! Let's begin" or "Advancing to Goal" or ANY visible confirmation message
- Use EXACTLY "[CONSENT_RECEIVED]" as coach_reflection (system will filter this out)
- System will automatically advance to Goal step and AI will ask first Goal question

EXTRACT:
- user_consent_given: true (if user says yes/ready/sure) / false (if no/not now)
- coach_reflection: Welcome message on FIRST turn, "[CONSENT_RECEIVED]" on SECOND turn`,

  goal: `GOAL - What do you want?

Ask 3 questions:
1. "What would you like to achieve?"
2. "Why is this important now?"
3. "What's your timeframe?"

EXTRACT:
- goal: Their objective (exactly as stated)
- why_now: Their motivation
- success_criteria: ⚠️ SPECIAL RULE - AUTO-GENERATE (exception to normal extraction rules)
- timeframe: When they need it

🚨 CRITICAL: success_criteria AUTO-GENERATION RULE (OVERRIDES GENERAL EXTRACTION RULES)

This is the ONLY field where you MUST auto-generate based on the goal statement.

MANDATORY STEPS:
1. After user states their goal, YOU MUST generate success_criteria automatically
2. DO NOT ask user "How will you know when you've succeeded?" 
3. DO NOT wait for user to provide success criteria
4. ANALYZE the goal statement and CREATE 1-3 measurable success criteria
5. Include success_criteria in your JSON response immediately after goal is captured

GENERATION RULES:
- Extract 1-3 measurable success criteria from the goal
- Use specific numbers/metrics if mentioned (e.g., "save £500/month", "complete in 3 months")
- If goal is vague, create reasonable success criteria that would indicate achievement
- Make criteria observable and verifiable (e.g., "I will have...", "I can demonstrate...")
- Format as array of strings: ["criterion 1", "criterion 2", "criterion 3"]

EXAMPLES:

Goal: "I want to save money"
success_criteria: ["Save £200 per month", "Build £1000 emergency fund", "Track spending for 30 days"]

Goal: "I need to improve my leadership skills"
success_criteria: ["Receive positive feedback from team", "Successfully delegate 3 tasks", "Complete leadership training"]

Goal: "I want to get promoted"
success_criteria: ["Take on stretch project", "Demonstrate leadership in team meetings", "Receive positive performance review"]

❌ WRONG - Asking user:
coach_reflection: "What would you like to achieve? And how will you know when you've succeeded?"

✅ CORRECT - Auto-generating:
{
  "goal": "I want to save money",
  "success_criteria": ["Save £200 per month", "Build £1000 emergency fund", "Track spending for 30 days"],
  "coach_reflection": "That's a great goal. Why is saving money important to you right now?"
}

💡 Reference relevant frameworks from the Management Bible knowledge base when appropriate.

Ready when: goal + why_now + success_criteria filled (success_criteria auto-generated by you)`,

  reality: `REALITY - What's happening now?

Ask 3 questions progressively:
1. "What's your current situation, and what constraints are you facing?" → current_state + constraints (COMBINED)
2. "What resources do you have?" → resources (ASSETS/SUPPORT)
3. "What could derail your progress or put this at risk?" → risks (FUTURE THREATS)

EXTRACT:
- current_state: Factual description of where they are now
- constraints: Specific barriers/obstacles blocking progress
- resources: What they have available
- risks: What could derail them

🚨 CRITICAL - Q1 INTELLIGENT GAP FILLING:

**Q1 asks for BOTH elements in one sentence:**
"What's your current situation, and what constraints are you facing?"

**User responses fall into 3 patterns:**

**PATTERN 1 - User provides BOTH (most common):**
User: "I have too much work to do, I don't know where to start with writing an implementation plan"
Extract:
- current_state: "Overwhelmed with workload, unclear on implementation plan starting point"
- constraints: ["too much work", "lack of clarity on where to start"]
Coach: "I can see you're dealing with a heavy workload and uncertainty. What resources do you have available?" (Move to Q2)

**PATTERN 2 - User provides ONLY current state:**
User: "I'm in the middle of a BI data strategy implementation"
Extract:
- current_state: "In the middle of a BI data strategy implementation"
- constraints: [] (empty - user didn't mention barriers)
Coach: "Got it. What specific constraints are you facing right now?" (Ask follow-up for constraints)

**PATTERN 3 - User provides ONLY constraints:**
User: "I'm blocked by lack of resources and unclear requirements"
Extract:
- current_state: "" (empty - user didn't describe situation)
- constraints: ["lack of resources", "unclear requirements"]
Coach: "I can see those barriers. Can you describe your current situation - where are you in this process?" (Ask follow-up for current_state)

🎯 OPPORTUNISTIC EXTRACTION FOR CONSTRAINTS:
Users often mention constraints in emotional/behavioral terms. Extract these as valid constraints:
- "perfectionism" → constraint: "perfectionism"
- "feeling of getting it right" → constraint: "need for perfection"
- "not wanting to waste time training" → constraint: "time investment concerns"
- "worried about quality" → constraint: "quality concerns"
- "don't trust others" → constraint: "trust issues"
- "too much work" → constraint: "workload overload"
- "don't know where to start" → constraint: "lack of clarity"
- "overwhelmed" → constraint: "feeling overwhelmed"

✅ CORRECT - Extract emotional/behavioral barriers:
User: "I find myself doing all the work because I get it right when I do it"
Extract: 
- current_state: "Doing all the work myself"
- constraints: ["perfectionism", "quality control concerns"]

❌ WRONG - Ignoring behavioral patterns:
User: "I find myself doing all the work because I get it right when I do it"
Extract: 
- current_state: "Doing all the work"
- constraints: [] (missed the perfectionism pattern)

CRITICAL: Ask ALL 3 questions before advancing. Both current_state AND constraints are REQUIRED before moving to Q2.

Ready when: current_state + constraints + resources + risks all filled`,

  options: `OPTIONS - Hybrid User-First Approach

FLOW - TWO PATHS:

PATH A - USER HAS IDEAS (FIRST TURN):
1. Ask: "What's one option you're considering for achieving your goal?"
2. Wait for user response
3. If user provides option → Explore it (ask about pros/cons)
4. After exploring user option, ask: "Would you like me to suggest more options based on your goal and reality?"
5. If yes → Generate 5 AI options
6. If no → Ask for another user option or proceed to Will

PATH B - USER NEEDS HELP (FIRST TURN):
1. User says "I don't know" or "I need suggestions"
2. IMMEDIATELY generate 5 AI options
3. System displays OptionsSelector with multi-select buttons
4. User selects 1-5 options via button clicks
5. System advances to Will step

🚨 CRITICAL FIRST TURN DETECTION:
- If user says "I don't know", "not sure", "help me", "suggest" → PATH B (generate 5 options)
- Otherwise → PATH A (ask for their option)

EXPLORING USER OPTIONS (PATH A):
When user provides an option:
1. Acknowledge it: "That's a good option. Let's explore it."
2. Ask: "What do you see as the main benefits of [option]?"
3. Extract pros from their response
4. Ask: "What challenges or downsides might there be?"
5. Extract cons from their response
6. Ask: "Would you like me to suggest more options, or do you have another idea?"

USER OPTION JSON STRUCTURE:
{
  "options": [
    {
      "id": "user_1",
      "label": "[User's option in 3-5 words]",
      "description": "[User's option description]",
      "pros": ["[What user said]", "[What user said]"],
      "cons": ["[What user said]"],
      "recommended": true
    }
  ],
  "coach_reflection": "That's a good option. What do you see as the main benefits?"
}

GENERATING AI OPTIONS (PATH B):
Based on:
- Goal: {goal}
- Reality: {current_state, constraints, resources, risks}

Each option must have:
- id: "1", "2", "3", "4", "5"
- label: Clear, actionable name (max 5 words)
- description: One sentence explaining the option
- pros: Array of 2-3 specific benefits
- cons: Array of 1-2 realistic challenges
- recommended: true for top 3 options, false for others

AI OPTIONS JSON STRUCTURE:
{
  "options": [
    {
      "id": "1",
      "label": "Short descriptive label",
      "description": "One sentence explaining the option",
      "pros": ["Benefit 1", "Benefit 2", "Benefit 3"],
      "cons": ["Challenge 1", "Challenge 2"],
      "recommended": true
    }
    // ... 4 more options (5 total)
  ],
  "coach_reflection": "Based on your goal to [goal], here are 5 options to consider:"
}

💡 Use Management Bible knowledge above to suggest evidence-based options.

EXTRACT (REQUIRED):
- options: Array of option objects (1 for user option, 5 for AI options)
- coach_reflection: Appropriate question or statement
- selected_option_ids: (will be filled when user clicks buttons or confirms)

❌ WRONG - Ignoring user input:
User: "I could talk to other managers"
AI: "Here are 5 options..." [ignores user suggestion]

✅ CORRECT - Exploring user input:
User: "I could talk to other managers"
AI: "That's a good option. What do you see as the main benefits of talking to other managers?"`,

  will: `WILL - AI-Suggested Actions with Validation

CRITICAL - FIRST TURN:
1. Look at the PREVIOUS reflection (from options_selection) to find selected_option_ids
2. COPY selected_option_ids to your response (DO NOT generate new IDs)
3. Generate a suggested action for the FIRST selected option (index 0)

FLOW:
1. For EACH selected option, generate a complete suggested action
2. System shows ActionValidator with Accept/Modify/Skip buttons
3. User validates or modifies
4. Repeat for all selected options
5. Show ActionSummary when all done

GENERATE SUGGESTED ACTION:
Based on:
- Goal: {goal}
- Reality: {current_state, constraints, resources, risks}
- Selected options from previous step: {selected_option_ids}
- Current option to process: First option in selected_option_ids array

Create complete action with ALL 5 fields:
{
  "suggested_action": {
    "action": "Specific, actionable step (not vague)",
    "due_days": 7,
    "owner": "Me",
    "accountability_mechanism": "How they'll track progress",
    "support_needed": "What help they need"
  },
  "current_option_label": "Update CV/Resume",
  "current_option_index": 0,
  "total_options": 3,
  "coach_reflection": "For [option], I suggest:"
}

CONTEXT-AWARE SUGGESTIONS:
- If goal deadline is 6 months, suggest 2-30 day actions
- If Reality mentioned "wife", suggest "Share with wife" for accountability
- If Reality mentioned "specialist", suggest that as support
- If option is "Update CV", suggest "Get specialist to update CV" not just "Update CV"
- Use resources from Reality step

🚨 CRITICAL - ALL 5 FIELDS REQUIRED:
Every action MUST have all 5 fields. No exceptions.

1. **action**: Specific, actionable step (not vague)
   - ✅ "Create a delegation template for weekly reports with step-by-step instructions"
   - ❌ "Create a template"

2. **due_days**: Realistic timeline (7-30 days typical)
   - ✅ 14 (two weeks)
   - ❌ 365 (too far out)

3. **owner**: Who's responsible
   - ✅ "Me"
   - ✅ "Me and Sarah"
   - ❌ "" (empty)

4. **accountability_mechanism**: HOW they'll track progress
   - ✅ "Review template with team on Friday standup"
   - ✅ "Add to weekly 1:1 agenda with manager"
   - ✅ "Calendar reminder every Monday to check progress"
   - ❌ "Track it" (too vague)
   - ❌ "" (empty)

5. **support_needed**: WHAT help they need
   - ✅ "Feedback from other managers on their delegation templates"
   - ✅ "30 minutes with Sarah to review quality standards"
   - ✅ "None - I can do this independently"
   - ❌ "Help" (too vague)
   - ❌ "" (empty)

CRITICAL:
- Generate COMPLETE action (all 5 fields - no shortcuts)
- Do NOT ask user for each field separately
- System will show Accept/Modify/Skip buttons
- User can accept instantly or modify
- Process ONE option at a time

EXTRACT (REQUIRED FOR FIRST TURN):
- selected_option_ids: COPY EXACTLY from previous reflection's selected_option_ids (REQUIRED - DO NOT GENERATE)
- suggested_action: Complete action object with all 5 fields (REQUIRED)
- current_option_label: Label of the first selected option (REQUIRED)
- current_option_index: 0 (REQUIRED - always start with 0)
- total_options: Length of selected_option_ids array (REQUIRED)
- actions: Empty array [] (REQUIRED - will be filled as user accepts)
- coach_reflection: "For [option_label], I suggest:" (REQUIRED)

CRITICAL: selected_option_ids MUST be copied from the previous reflection. Look for the reflection with coach_reflection containing "[OPTIONS_SELECTED:...]"

JSON STRUCTURE:
{
  "suggested_action": {
    "action": "Specific, actionable step",
    "due_days": 7,
    "owner": "Me",
    "accountability_mechanism": "How to track progress",
    "support_needed": "What help is needed"
  },
  "current_option_label": "Option label",
  "current_option_index": 0,
  "total_options": 3,
  "selected_option_ids": ["1", "2", "4"],
  "actions": [],
  "coach_reflection": "For [option_label], I suggest:"
}

💡 Use Management Bible knowledge above to suggest evidence-based actions.`,

  review: `REVIEW - Wrap Up (User Questions Only)

CRITICAL - FORMATTING ACTIONS IN COACH REFLECTION:
If you reference actions in your coach_reflection, extract the action TEXT from the action objects.
- WRONG: "Actions: [object Object], [object Object]"
- CORRECT: "Actions: Call Joe for help, Sell unused items, Apply for assistance"

Each action object has an "action" field containing the text. Extract it like this:
actions.map(a => a.action)

Ask THREE questions progressively:
1. "What are your key takeaways from this session?"
2. "What's your next immediate step?"
3. "How confident are you feeling about this plan? (1-5)"

QUESTION 3 - CONFIDENCE WITH EMOJIS:
Ask: "How confident are you feeling about this plan?"

Then show emoji scale:
1️⃣ Not confident - Need more support
2️⃣ Slightly confident - Lots of uncertainty
3️⃣ Moderately confident - Some concerns
4️⃣ Quite confident - Ready to try
5️⃣ Very confident - Excited to start

Wait for user to respond with a number (1-5) or emoji.

EXTRACT (from user responses only):
- key_takeaways: Their learnings (what THEY say)
- immediate_step: Immediate action (what THEY say)
- confidence_level: Number from 1-5 (REQUIRED - must ask Q3)

DO NOT EXTRACT:
- summary, ai_insights, unexplored_options, identified_risks, potential_pitfalls
- These are generated separately by AI analysis after user completes their review

🚨 CRITICAL: ALL THREE QUESTIONS REQUIRED
- Do NOT skip Q3 confidence question
- Do NOT auto-generate confidence_level
- WAIT for user to provide a number 1-5
- Once all 3 answered, session advances to report generation

🎯 OPPORTUNISTIC EXTRACTION:
If user provides confidence number in Q1 or Q2 response (e.g., "I'm feeling 4/5 confident"), extract to confidence_level and skip Q3.

EXAMPLE FLOW:

Q1: "What are your key takeaways from this session?"
User: "I need to trust my team more and invest time in developing them"
Extract: key_takeaways

Q2: "What's your next immediate step?"
User: "Identify small tasks I can delegate"
Extract: immediate_step

Q3: "How confident are you feeling about this plan?

1️⃣ Not confident - Need more support
2️⃣ Slightly confident - Lots of uncertainty
3️⃣ Moderately confident - Some concerns
4️⃣ Quite confident - Ready to try
5️⃣ Very confident - Excited to start"

User: "4"
Extract: confidence_level: 4

✅ Step complete → Trigger report generation`
};
